# -*- coding: utf-8 -*-
"""webscrap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OanPADcQRBaDE1w_zqyNOUTOeLvUTMoF
"""

import requests

from bs4 import BeautifulSoup

import pandas as pd

books = []
for i in range (1,5):
  url = "https://books.toscrape.com/catalogue/page-3.html"
  response = requests.get(url)
  response = response.content
  soup = BeautifulSoup(response, 'html.parser')
  ol = soup.find('ol')
  articles = ol.find_all('article', class_='product_pod')

  for article in articles:
    image = article.find('img')
    title = image.attrs['alt']
    star = article.find('p')
    star = star['class'][1]
    price = article.find('p', class_='price_color').text
    price = float(price[1:])
    books.append([title, price, star])
    print(price)

df = pd.DataFrame(books, columns=['Ttile', 'Price', 'Star Rating'] )

df.to_csv('books.csv')